### ISSUE TITLE
Window color schemes

### ISSUE THREAD

**Issue by danirod** [danirod/cartero#100]
Since libadwaita 1.6 migrates the color system of its theme to CSS variables, it is now very easy to override the colors of the application, with interesting consequences. Once #96 lands, it would be interesting to have official support for some colorschemes.

Note that these don't seem to affect the GtkSource color schemes yet.

Also, wondering if rather than setting the `--accent-bg-color` variable, I can set the different `--accent-*` color variables so that if you have your system-wide accent color set to blue, red, green... it uses the closest one from the color scheme that matches the semantic accent color set on your system.

Here are some examples. To test these, open the GTK inspector by pressing Ctrl + Shift + I, then go to the CSS tab and paste the following snippets into the area. Press the :pause_button: button to toggle custom CSS styles. Note that in my computer the performance of this action is very poor and very laggy, so the themes haven't been thoughtfully tested yet, this is just an example or a proof of concept.

## Nord

```css
window {
  --headerbar-bg-color: #3b4252;
  --headerbar-fg-color: #eceff4;
  --headerbar-backdrop-color: #2e3440;
  --window-bg-color: #434c5e;
  --card-bg-color: #4c566a;
  --card-fg-color: #eceff4;
  --accent-bg-color: #81a1c1;
  --window-fg-color: #eceff4;
}
```
![A screenshot of Cartero with the color scheme set to Nord](https://github.com/user-attachments/assets/676a694c-b08f-46b3-9c4f-b6f801ac9583)

## Catpuccin

```css
window {
  --headerbar-bg-color: #292c3c;
  --headerbar-fg-color: #c6d0f5;
  --headerbar-backdrop-color: #232634;
  --window-bg-color: #303446;
  --card-bg-color: #414559;
  --card-fg-color: #c6d0f5;
  --accent-bg-color: #ca9ee6;
  --window-fg-color: #c6d0f5;
}
```

![A screenshot of Cartero with the color scheme set to Catpuccin](https://github.com/user-attachments/assets/da9e2bb5-9c28-4c11-becc-4ef543127e08)

## Solarized

```css
window {
  --headerbar-bg-color: #073642;
  --headerbar-fg-color: #eee8d5;
  --headerbar-backdrop-color: #002b36;
  --window-bg-color: #073642;
  --card-bg-color: #586e75;
  --card-fg-color: #eee8d5;
  --accent-bg-color: #2aa198;
  --window-fg-color: #eee8d5;
}
```

![A screenshot of Cartero with the color scheme set to Solarized](https://github.com/user-attachments/assets/67cb8a89-3531-424a-8d29-c7cbe4b01278)

## Gruvbox

```css
window {
  --headerbar-bg-color: #282828;
  --headerbar-fg-color: #ebdbb2;
  --headerbar-backdrop-color: #282828;
  --window-bg-color: #3c3836;
  --card-bg-color: #504945;
  --card-fg-color: #ebdbb2;
  --accent-bg-color: #b8bb26;
  --window-fg-color: #ebdbb2;
}
```

![A screenshot of Cartero with the color scheme set to Gruvbox](https://github.com/user-attachments/assets/dc7215f1-95a2-4a41-a29b-b34935ffd401)
