### ISSUE TITLE
Params table and URL field still not in sync if URL starts with variable

### ISSUE THREAD

**Issue by danirod** [danirod/cartero#202]
When the URL is set to something that starts with a variable, even if the variable is defined, wellformed and set to an fully schemed URL, the parameters table does not sync with the contents of the URL bar.

As an example, the following request:

```toml
version = 1
url = "{{ROOT}}/?a=4&b=5"
method = "GET"

[variables]
ROOT = "http://localhost:3000"
```

Does not keep the table in sync with the URL bar and glitches happen when modifications are made. For instance, if you add `https://` to the beginning of the URL, suddenly the table gets overwritten by the contents of the URL bar.

https://github.com/user-attachments/assets/a407d35f-3d97-4311-8b57-0ad82cc87d84
