### ISSUE TITLE
Persist duplicate KeyValue items

### ISSUE THREAD

**Issue by danirod** [danirod/cartero#24]
Currently, storing a key-value table (such as headers or variables) uses a HashMap<String, String> data structure, which means that for a standard header table, everything works fine:

| x | Header | Value |
| - | --- | --- |
| x | Accept | application/json |
|  | Content-Type | application/json |

Stored as 

```toml
[headers]
Accept = "application/json"
Content-Type = { active = false, value = "application/json" }
```

However, since the user interface allows the user to paste duplicate keys, persisting after adding duplicate values may trigger unexpected consecuences. HashMaps cannot have duplicate keys, so only one of the values for each duplicate key will be persisted, usually the one that comes after.

| x | Header | Value |
| - | --- | --- |
| x | ~~Accept~~ | ~~application/json~~ |
|  | Content-Type | application/json |
| x | Accept | application/ld+json |

Stored as 

```toml
[headers]
Accept = "application/ld+json"
Content-Type = { active = false, value = "application/json" }
```

What if this is just temporary and the user is actually using the checkboxes to toggle one or another? The saved file should reflect that, while being retrocompatible.

So just like it was done to accept both strings and inline tables as values for a key-value entry, a third type should be added that is actually an array of either strings or inline tables, which means that the following could be totally acceptable:

| x | Header | Value |
| - | --- | --- |
|   | ~~Accept~~ | ~~application/json~~ |
|  | Content-Type | application/json |
| x | Accept | application/ld+json |

Stored as 

```toml
[headers]
Accept = [
  { value = "application/json", active = false },
  "application/ld+json"
]
Content-Type = { active = false, value = "application/json" }
```

Note that the order in which keys are persisted is still not relevant, but since an item overrides any item with the same key that is above in the table, it is important for entries with the same name to be persisted in the same order as they appear in the user interface.
